version: '3.8'

services:
  asp-services-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asp-services-web
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_EMAILJS_SERVICE_ID=${NUXT_PUBLIC_EMAILJS_SERVICE_ID}
      - NUXT_PUBLIC_EMAILJS_TEMPLATE_ID=${NUXT_PUBLIC_EMAILJS_TEMPLATE_ID}
      - NUXT_PUBLIC_EMAILJS_TEMPLATE_ID_QUOTE=${NUXT_PUBLIC_EMAILJS_TEMPLATE_ID_QUOTE}
      - NUXT_PUBLIC_EMAILJS_PUBLIC_KEY=${NUXT_PUBLIC_EMAILJS_PUBLIC_KEY}
      - NUXT_PUBLIC_EMAILJS_SERVICE_ID_CLIENT=${NUXT_PUBLIC_EMAILJS_SERVICE_ID_CLIENT}
      - NUXT_PUBLIC_EMAILJS_TEMPLATE_ID_QUOTE_CLIENT=${NUXT_PUBLIC_EMAILJS_TEMPLATE_ID_QUOTE_CLIENT}
      - NUXT_PUBLIC_EMAILJS_PUBLIC_KEY_CLIENT=${NUXT_PUBLIC_EMAILJS_PUBLIC_KEY_CLIENT}
      - NUXT_PUBLIC_SITE_URL=${NUXT_PUBLIC_SITE_URL}
      - NUXT_PUBLIC_IMAGEKIT_URL_ENDPOINT=${NUXT_PUBLIC_IMAGEKIT_URL_ENDPOINT}
      - NUXT_PUBLIC_IMAGEKIT_PUBLIC_KEY=${NUXT_PUBLIC_IMAGEKIT_PUBLIC_KEY}
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
    networks:
      - asp-network

networks:
  asp-network:
    driver: bridge
